#!/usr/bin/env node
// alfred init — provision a tenant, workspace (optional), and API key.
//
// USAGE
//   alfred init [--profile=<coding|web|both>] [--name <display-name>]
//              [--backend=<sqlite|postgres>] [--db-path <p>|--db-connection <u>]
//              [--cwd <path>] [--print-only|--non-interactive]
//
// PROFILES
//   coding (default)  - coding_agent_only + sqlite + writes .alfred/config.json
//   web               - human_agent + postgres, NO workspace binding, prints web
//                        setup steps for ChatGPT/Claude/Gemini
//   both              - hybrid_with_human + postgres, writes workspace config AND
//                        prints web setup steps
//
// EXAMPLES
//   alfred init                                    # coding profile, sqlite, prompt for backend
//   alfred init --profile=web --name my-mem        # human_agent, postgres, web setup
//   alfred init --profile=both --name shared        # hybrid
//   alfred init --non-interactive --name acme        # CI mode: no prompts
//   alfred init --print-only                       # show plan without executing
//
// API KEY
//   The API key is generated by the registry and is the credential for ALL agents.
//   It is shown ONCE. Save it.

import { writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";

import {
  createTenantService,
  createUserService,
  sha256OfPath
} from "../../memory/src/index.js";
import { openRegistry } from "../src/registry/store-factory.js";
import {
  resolveProfile,
  buildInitPlan,
  nextStepsFor
} from "../src/profiles/init-profiles.js";

function parseArgs(argv) {
  const out = { _: [] };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a.startsWith("--")) {
      // Support both --key value and --key=value forms.
      let k, v;
      const eq = a.indexOf("=");
      if (eq !== -1) {
        k = a.slice(2, eq);
        v = a.slice(eq + 1);
      } else {
        k = a.slice(2);
        v = argv[i + 1];
      }
      if (v === undefined || v.startsWith("--")) { out[k] = true; } else { out[k] = v; i += 1; }
    } else { out._.push(a); }
  }
  return out;
}

function readStdin(question) {
  if (!process.stdin.isTTY) return Promise.resolve(null);
  return new Promise((resolve) => {
    process.stderr.write(question);
    process.stdin.setEncoding("utf8");
    let buf = "";
    const onData = (chunk) => {
      buf += chunk;
      if (buf.includes("\n")) {
        process.stdin.removeListener("data", onData);
        process.stdin.pause();
        resolve(buf.trim());
      }
    };
    process.stdin.resume();
    process.stdin.on("data", onData);
  });
}

function writeWorkspaceConfig(cwd, payload) {
  const cfgDir = join(cwd, ".alfred");
  if (!existsSync(cfgDir)) mkdirSync(cfgDir, { recursive: true });
  writeFileSync(join(cfgDir, "config.json"), JSON.stringify(payload, null, 2) + "\n");
  return join(cfgDir, "config.json");
}

export async function run(argv = [], env = process.env) {
  const args = parseArgs(argv);

  // Args + profile resolution.
  const profileName = args.profile || "coding";
  const profile = resolveProfile(profileName);
  if (!profile) {
    process.stderr.write(`Unknown profile '${profileName}'. Available: coding, web, both.\n`);
    return 2;
  }
  const cwd = args.cwd || env.ALFRED_WORKDIR || process.cwd();
  const print_only = !!args["print-only"];
  const non_interactive = !!args["non-interactive"];

  // Build the plan.
  const planResult = buildInitPlan({
    profileName,
    storage: args.backend,
    db_path: args["db-path"],
    db_connection: args["db-connection"],
    name: args.name,
    cwd
  });
  if (!planResult.ok) {
    process.stderr.write(`Init plan error: ${planResult.error}\n`);
    return 2;
  }
  const plan = planResult.plan;

  // Interactive prompt: ask for name (default: derived) and confirm.
  if (!args.name && process.stdin.isTTY && !non_interactive) {
    const answer = await readStdin(`Display name [${plan.display_name}]: `);
    if (answer) plan.display_name = answer;
  }
  if (profileName === "coding" && !args.backend && process.stdin.isTTY && !non_interactive) {
    const answer = await readStdin("Backend [sqlite|postgres] (default sqlite): ");
    if (answer === "postgres") {
      process.stderr.write("Switching to postgres requires --db-connection. Use --backend=postgres --db-connection=postgres://...\n");
      return 2;
    }
  }

  // Confirm before executing.
  if (!print_only && process.stdin.isTTY && !non_interactive) {
    process.stderr.write("\n# Plan\n");
    for (const [k, v] of Object.entries(plan)) {
      process.stderr.write(`  ${k}: ${typeof v === "string" ? v : JSON.stringify(v)}\n`);
    }
    const answer = await readStdin("\nProceed? [y/N] ");
    if (!answer || !/^y(es)?$/i.test(answer)) {
      process.stderr.write("Cancelled.\n");
      return 1;
    }
  }

  if (print_only) {
    process.stdout.write(JSON.stringify({ ok: true, plan, registry_path: undefined }, null, 2) + "\n");
    return 0;
  }

  // Execute.
  const registry = await openRegistry();
  try {
    const tenantService = createTenantService({ store: registry.tenants });

    const tenant = await tenantService.provisionTenant({
      kind: plan.tenant_kind,
      storage_backend: plan.storage,
      display_name: plan.display_name,
      db_path: plan.db_path,
      db_connection: plan.db_connection
    });

    let workspace = null;
    let workspaceConfigPath = null;
    if (plan.write_workspace_config) {
      const workspaceHash = sha256OfPath(plan.cwd);
      const existing = await registry.tenants.findWorkspaceByHash(workspaceHash);
      workspace = existing
        ? existing
        : await tenantService.registerWorkspace({
            workspace_hash: workspaceHash,
            workspace_path: plan.cwd
          });
      await tenantService.grantAccess({
        workspace_id: workspace.id,
        tenant_id: tenant.id,
        access: "owner",
        inherited: false
      });
    }

    const userService = createUserService({ store: registry.users });
    const { apiKey, key } = await userService.provisionApiKey({ tenant_id: tenant.id, label: "init" });

    const result = {
      ok: true,
      profile: plan.profile,
      tenant_id: tenant.id,
      workspace_id: workspace?.id ?? null,
      api_key: apiKey,
      key_id: key.id,
      key_prefix: key.key_prefix,
      registry_path: registry.dbPath,
      next_steps: nextStepsFor(plan.next_steps_kind, {
        tenant_id: tenant.id,
        workspace_id: workspace?.id,
        api_key: apiKey,
        registry_path: registry.dbPath
      })
    };

    if (plan.write_workspace_config) {
      const cfg = {
        registry: registry.dbPath,
        tenant: {
          id: tenant.id,
          kind: tenant.kind,
          storage_backend: tenant.storage_backend,
          db_path: tenant.db_path,
          db_connection: tenant.db_connection
        },
        workspace_id: workspace.id,
        workspace_hash: sha256OfPath(plan.cwd),
        api_key: apiKey,
        key_id: key.id,
        key_prefix: key.key_prefix,
        created_at: new Date().toISOString()
      };
      result.config_path = writeWorkspaceConfig(plan.cwd, cfg);
    }

    // Machine-readable JSON.
    process.stdout.write(JSON.stringify(result, null, 2) + "\n");

    // Human-readable next steps on stderr.
    process.stderr.write("\n" + "=".repeat(60) + "\n");
    process.stderr.write("ALFRED MEMORY INITIALIZED\n");
    process.stderr.write("=".repeat(60) + "\n\n");
    process.stderr.write(`Profile:        ${plan.profile}\n`);
    process.stderr.write(`Tenant:         ${tenant.id} (${tenant.kind})\n`);
    process.stderr.write(`Backend:        ${plan.storage}\n`);
    if (plan.db_path) process.stderr.write(`Tenant DB:      ${plan.db_path}\n`);
    if (plan.db_connection) process.stderr.write(`Tenant DB:      ${plan.db_connection}\n`);
    process.stderr.write(`Registry:       ${registry.dbPath}\n`);
    if (workspace) process.stderr.write(`Workspace:      ${workspace.id} (${plan.cwd})\n`);
    if (result.config_path) process.stderr.write(`Config:         ${result.config_path}\n`);
    process.stderr.write(`API key prefix: ${key.key_prefix}\n`);
    process.stderr.write(`\n>>> API KEY (save this, shown only once):\n>>> ${apiKey}\n\n`);

    process.stderr.write("Next steps:\n");
    for (const line of result.next_steps) {
      process.stderr.write(line + "\n");
    }
    return 0;
  } catch (err) {
    process.stderr.write(`Init failed: ${err.message}\n`);
    if (err.details) process.stderr.write(JSON.stringify(err.details, null, 2) + "\n");
    return 1;
  } finally {
    registry.close();
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  if (!process.stdin.isTTY) {
    process.env.ALFRED_INIT_NO_PROMPT = "1";
  }
  process.exit(await run(process.argv.slice(2)));
}
